version: "3.9"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
    ports: ["3306:3306"]
    command: ["--default-authentication-plugin=mysql_native_password"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
