app:
  http_addr: ":8080"
mysql:
  dsn: "root:root@tcp(127.0.0.1:3306)/orders?parseTime=true"
redis:
  addr: "127.0.0.1:6379"
rabbitmq:
  url: "amqp://guest:guest@127.0.0.1:5672/"
kafka:
  brokers: ["127.0.0.1:9092"]
security:
  jwt_secret: "dev-secret"
  issuer: "go-order-api"
  audience: "go-order-api-clients"
  ttl: 30
grpc_server:
  target: "localhost:50051"
  use_tls: false
  timeout: "10s"
crypto:
  key_id: "v1"
  aes256_b64url: "e_LQd-NRhR-n41rch_jWLCeOw-XX-qpcBm0fzzUTS_0"
  rsa_pub_pem: "-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsnW2DPRyEY3n0FT0QNk+
fYLs72KNXN1mFPk0INxpo8uWieBPqocFsu3NvqgLkHgoKM1fmEbKLnisVLb5xdFv
2r2P5Gy40Ko68j+Q4HfE4Z9pI7Uzg4H3xQm8G6zpBuKsfqemqtNY4NQC+vxA45yq
XNigyLRZcFKIZR0xgEs2hjmfnq2m2wS/4aMw/D+D/zjGjr7kS3gwF1kAWQnUR3M+
dhKFLwt2lyf12h1q69BXarRgO5zAF/t1t+QKdwCDGX4F4erTy13JsUVjJm9EAZ8z
g9GbSFHEQCLIGrEl+A49JfllDIQMD0144Cpumvmexcc+leMVD9KjOYCusYNeFSRw
nQIDAQAB
-----END PUBLIC KEY-----"
  rsa_pri_pem: "-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCydbYM9HIRjefQ
VPRA2T59guzvYo1c3WYU+TQg3Gmjy5aJ4E+qhwWy7c2+qAuQeCgozV+YRsoueKxU
tvnF0W/avY/kbLjQqjryP5Dgd8Thn2kjtTODgffFCbwbrOkG4qx+p6aq01jg1AL6
/EDjnKpc2KDItFlwUohlHTGASzaGOZ+erabbBL/hozD8P4P/OMaOvuRLeDAXWQBZ
CdRHcz52EoUvC3aXJ/XaHWrr0FdqtGA7nMAX+3W35Ap3AIMZfgXh6tPLXcmxRWMm
b0QBnzOD0ZtIUcRAIsgasSX4Dj0l+WUMhAwPTXjgKm6a+Z7Fxz6V4xUP0qM5gK6x
g14VJHCdAgMBAAECggEAewTLxyhmzZUN3L4DVgSroCe1nttH6WExcnnLJm/qXqAE
GO1I3ZuQISTutGPw/NjnjiDsqfL6gohq+0ba7TOPsLEF1Qfhau4+Diole6b0UDfs
aVIKvbfFDc3FHyrVxApTsEdvi8h/NxTPLSbgsEaZ5cDrLQ+tq9Eo9tLmAbNXVbSR
setYUdHjxb2gijhGlmUKENyJE7vIOkQGQ8VOVarYQInXy2isORIY8/pVzk/ar/V9
bJe4NWgUvn/LS1GIArnSY3tYEuwkL3MUv0cOj5wXlvongX+XSQi8C4fTAN4Xo0jD
eEVV6h5U9NIdy9cj+1ZBHcypl3fzIlVvEwmec8lNnQKBgQDnAkRR4ooZbnZWIkV8
7HtMf0gWTjrfYmSG86YcFke1YwBGcJ50mgzKI0BWI+aFkBmSVovXY2QavFwo2TTW
oLdtGrE44+N2nSCv8J7XC77vc0Vpngb3mBchQdoiH66NB+Z6zvRSZV68EmwTX8Ll
K7jG62dPTYN2gtf9gU//ZeJyLwKBgQDFxByGhLh5oRKJoJYdf3BhTbg4YMv7xRkC
amVEEQuK0sQigXkkXR6DkC0T6nnTNwgYBOT/6NGSvRTw8DBffVO2JA0Vy1SipsJs
TsPrnGE1TvSR7m64o3GyCAmqbZG0RNqUPQBkqYdiS77lmT1yVIsBYv6yc8F7y4O1
qBRO9pFS8wKBgCL0v9vYOOeCRJviEbvGmR3JQOJHMjdtTyLwqZkkcfNrqLYAAqpI
SVkpHmoqgo6BcK0pNX4BRzuYdyWjQJCdv0PePyUJrvja7ABTm+WUnG7ldYJ27Dz5
Ib7hlR2Gx8YFhQXeXTA+sKgq7Xm9CuPcytgm9PoWE6eSQxbUQ4O1Kh/3AoGBAKMh
/hXIbROHlm8IlEuIz/6zyX5X+muYTeT8NsRK+yZsbXW5L2Cbn4wO5eBDznI4Nuj5
QJ0IQ7ezWQ7WUlCyZNceLd0IeKwiusX0wxAbUuRSWNP3xkVwLV0Z3D9FWqdFFLir
CSP/47llmfZyzYj9zBw8uLQjYDrpyZ+TIg1wvreZAoGAL4aS4vEcxF7MwumSHh8u
wStC8PuzPi1AVn6XNuVwSPSIVsQ4Ytv4dUHTX2n6/ATpTmNySNE16iGQUHXMQ+Bg
P8/btmCSmeXIweQkHMnTeQzaTSxnVojJGzd+1j1R67sncLZ14ZBEbmK2MOX3OvwX
l6X1yMlTPbLfWm3/WJI84T8=
-----END PRIVATE KEY-----"
